import Head from "next/head";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Medium Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Medium 2.0</h1>
    </div>
  );
}
